services:
  vote:
    build:
      context: ./vote
    depends_on:
      - redis
    ports:
      - "80:80"

  result:
    build:
      context: ./result
    depends_on:
      - postgres
    ports:
      - "3000:4000"

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"

  redis:
    image: redis:5.0-alpine3.10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=vote

volumes:
  postgres_data:
  redis_data: