name: cicd tp
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build docker image vote
        run: docker build -t lestof/vote:latest ./vote
      - name: Build docker image result
        run: docker build -t lestof/result:latest ./result
      - name: Build docker image worker
        run: docker build -t lestof/worker:latest ./worker

      - name: push docker image vote
        run: docker push lestof/vote:latest
      - name: push docker image result
        run: docker push lestof/result:latest
      - name: push docker image worker
        run: docker push lestof/worker:latest